eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.120.9:8081/eureka/
  instance:
    prefer-ip-address: true #使用IP地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
spring:
  application:
    name: gateway
server:
  port: 8080
zuul:
  routes:
    service1: /service1/**
    service2: /service2/**